/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
    // Deletes ALL existing entries
    await knex("itineraries").del();
    await knex("itineraries").insert([
        {
            id: 1,
            trip_id: 1,
            title: "Day Trip to Pillow World",
            description: "Exploring the comfy depths of the Multiverse",
            start: "2025-03-05T00:00:00",
            end: "2025-03-06T00:00:00",
            all_day: true,
        },
        {
            id: 2,
            trip_id: 1,
            title: "Day Trip to Baby World",
            description: "",
            start: "2025-03-07T09:00:00",
            end: "2025-03-07T18:00:00",
            all_day: false,
        },
        {
            id: 3,
            trip_id: 1,
            title: "Exploration of Rick's Garage",
            description: "A deep dive into interdimensional gadgets and experiments.",
            start: "2025-03-04T10:00:00",
            end: "2025-03-04T17:00:00",
            all_day: false,
        },
        {
            id: 4,
            trip_id: 1,
            title: "Vacation on Planet Blobulus",
            description: "A relaxing getaway in a world of sentient jello creatures.",
            start: "2025-05-03T02:00:00",
            end: "2025-05-03T00:00:00",
            all_day: true,
        },
        {
            id: 5,
            trip_id: 1,
            title: "Flight to Multiverse",
            description: "Arrive 3 hours early!",
            start: "2025-03-02T07:00:00",
            end: "2025-03-02T10:00:00",
            all_day: false,
        },
        {
            id: 6,
            trip_id: 1,
            title: "Flight Home",
            description: "Don't forget passport!",
            start: "2025-03-09T13:00:00",
            end: "2025-03-09T16:00:00",
            all_day: false,
        },
        {
            id: 7,
            trip_id: 2,
            title: "Beach Day at Goo Lagoon",
            description: "Relaxation, volleyball, and jellyfish spotting.",
            start: "2025-07-05T09:00:00",
            end: "2025-07-05T16:00:00",
            all_day: false,
        },
        {
            id: 8,
            trip_id: 2,
            title: "Visit the Krusty Krab",
            description: "Enjoy a Krabby Patty while taking a tour of the kitchen.",
            start: "2025-07-07T11:00:00",
            end: "2025-07-07T13:00:00",
            all_day: false,
        },
        {
            id: 9,
            trip_id: 2,
            title: "Boatmobile Driving School",
            description: "Attempt to get a boating license.",
            start: "2025-07-10T14:00:00",
            end: "2025-07-10T17:00:00",
            all_day: false,
        },
        {
            id: 10,
            trip_id: 2,
            title: "Scuba Dive to Jellyfish Fields",
            description: "Explore underwater wonders and catch jellyfish.",
            start: "2025-07-15T08:00:00",
            end: "2025-07-15T13:00:00",
            all_day: false,
        },
        {
            id: 11,
            trip_id: 3,
            title: "Office Tour at Dunder Mifflin",
            description: "Meet the team and relive the sitcom's greatest moments.",
            start: "2025-08-08T10:00:00",
            end: "2025-08-08T12:00:00",
            all_day: false,
        },
        {
            id: 12,
            trip_id: 3,
            title: "Birthday Dinner at Alfredo's Pizza Cafe",
            description: "Celebrate with authentic pizza, not Pizza by Alfredo.",
            start: "2025-08-08T19:00:00",
            end: "2025-08-08T21:00:00",
            all_day: false,
        },
        {
            id: 13,
            trip_id: 3,
            title: "Day Trip to Lackawanna Coal Mine",
            description: "Explore the historic coal mine and learn its history.",
            start: "2025-08-09T09:00:00",
            end: "2025-08-09T13:00:00",
            all_day: false,
        },
        {
            id: 14,
            trip_id: 4,
            title: "Santa's Workshop Tour",
            description: "A magical experience with elves and toy-making secrets.",
            start: "2025-12-16T10:00:00",
            end: "2025-12-16T13:00:00",
            all_day: false,
        },
        {
            id: 15,
            trip_id: 4,
            title: "Reindeer Sleigh Ride",
            description: "A scenic ride through snow-covered landscapes.",
            start: "2025-12-17T15:00:00",
            end: "2025-12-17T17:00:00",
            all_day: false,
        },
        {
            id: 16,
            trip_id: 4,
            title: "Northern Lights Viewing",
            description: "A breathtaking night of auroras and stargazing.",
            start: "2025-12-20T20:00:00",
            end: "2025-12-20T23:00:00",
            all_day: false,
        },
        {
            id: 17,
            trip_id: 5,
            title: "Broadway Show",
            description: "Catch a top-rated performance at the heart of NYC.",
            start: "2026-02-11T19:00:00",
            end: "2026-02-11T22:00:00",
            all_day: false,
        },
        {
            id: 18,
            trip_id: 5,
            title: "Empire State Building Visit",
            description: "Panoramic views of the city from the observation deck.",
            start: "2026-02-12T10:00:00",
            end: "2026-02-12T12:00:00",
            all_day: false,
        },
        {
            id: 19,
            trip_id: 5,
            title: "Central Park Stroll",
            description: "Relax and enjoy the iconic park in winter's beauty.",
            start: "2026-02-13T14:00:00",
            end: "2026-02-13T16:00:00",
            all_day: false,
        },
    ]);
}
