/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
    // Deletes ALL existing entries
    await knex("list_items").del();
    await knex("list_items").insert([
        {
            id: 1,
            list_id: 1,
            item: "Toothbrush",
            description: "Don't forget to charge your toothbrush!",
            status: 1,
            category: "Toiletries",
        },
        {
            id: 2,
            list_id: 1,
            item: "Floss",
            description: "",
            status: 3,
            category: "Toiletries",
        },
        {
            id: 3,
            list_id: 1,
            item: "Sunscreen",
            description: "SPF 50 for sunny days.",
            status: 2,
            category: "Toiletries",
        },
        {
            id: 4,
            list_id: 1,
            item: "Passport",
            description: "Check the expiration date!",
            status: 2,
            category: "Travel Essentials",
        },
        {
            id: 5,
            list_id: 1,
            item: "Charger",
            description: "Phone and laptop chargers",
            status: 3,
            category: "Electronics",
        },
        {
            id: 6,
            list_id: 1,
            item: "Sneakers",
            description: "",
            status: 3,
            category: "Clothing",
        },
        {
            id: 7,
            list_id: 1,
            item: "Heels",
            description: "",
            status: 3,
            category: "Clothing",
        },
        {
            id: 8,
            list_id: 1,
            item: "Shampoo",
            description: "Travel-size preferred",
            status: 1,
            category: "Toiletries",
        },
        {
            id: 9,
            list_id: 2,
            item: "Renew credit card",
            description: "",
            status: 1,
            category: "Errands",
        },
        {
            id: 10,
            list_id: 2,
            item: "Clean house before leaving",
            description: "Don't forget to take out the trash!",
            status: 1,
            category: "Home",
        },
        {
            id: 11,
            list_id: 3,
            item: "Gifts for Friends",
            description: "Pick something thoughtful",
            status: 1,
            category: "Gift Ideas",
        },
        {
            id: 12,
            list_id: 3,
            item: "Gift Bags",
            description: "For wrapping presents",
            status: 3,
            category: "Gift Supplies",
        },
        {
            id: 13,
            list_id: 4,
            item: "Apples",
            description: "Fresh fruit for the trip",
            status: 1,
            category: "Snacks",
        },
        {
            id: 14,
            list_id: 4,
            item: "Snacks",
            description: "For the road trip",
            status: 2,
            category: "Snacks",
        },
        {
            id: 15,
            list_id: 4,
            item: "Water Bottles",
            description: "Stay hydrated!",
            status: 3,
            category: "Beverages",
        },
        {
            id: 16,
            list_id: 4,
            item: "Granola Bars",
            description: "Energy boost during the trip",
            status: 1,
            category: "Snacks",
        },
        {
            id: 17,
            list_id: 2,
            item: "Find house sitter",
            description: "Possibly the Ice King?",
            status: 3,
            category: "Home",
        },
        {
            id: 18,
            list_id: 3,
            item: "Thank You Cards",
            description: "For after the trip",
            status: 2,
            category: "Gift Supplies",
        },
        {
            id: 19,
            list_id: 2,
            item: "Take out cash",
            description: "",
            status: 2,
            category: "Errands",
        },
        {
            id: 20,
            list_id: 4,
            item: "Croissants",
            description: "For sandwiches or snacks",
            status: 3,
            category: "Deli",
        },
    ]);
}
